### ISSUE TITLE
Nro CAS distinto

### ISSUE THREAD

**Issue by luchomedrano** [gauss-ma/toxDB#1]
Hay compuestos, principalmente los metálicos, que tienen información correspondiente a otro nro CAS, ejemplo CAS No.7440-38-2 ARSÉNICO, que realmente la data que traemos es del ARSANO H3As con un CAS No.7784-42-1.
Otro ejemplo donde directamente no tienen que ver es Talio (el elemento), CAS: 7440-28-0, estamos trayendo al "Perfluorooctanoyl fluoride" que tiene CAS 335-66-0.
@ramespada te la asigno.

**Comment by ramespada** [comment]
CHEQUIAMOS LOS QUE **ESTEN BIEN**.

- [x] 139-13-9;ACIDO NITRILO-TRIACETICO
- [x] 107-02-8;ACROLEINA
- [x] 116-06-3;ALDICARB
- [x] 309-00-2;ALDRIN
- [x] 7429-90-5;ALUMINIO (TOTAL)
- [x] 7664-41-7;AMONIO (ug/1 NH4)
- [x] 7440-38-2;ARSENICO (TOTAL)
- [x] 1912-24-9;ATRAZINA
- [x] 7440-39-3;BARIO (TOTAL)
- [x] 22781-23-3;BENDIOCARB
- [x] 7440-41-7;BERILIO (TOTAL)
- [x] 319-84-6;BHC-ALFA
- [x] 319-85-7;BHC-BETA
- [x] 111-44-4;BIS (2-CLOROETIL) ETER
- [x] 542-88-1;BIS (CLOROMETIL) ETER
- [x] 108-60-1;BIS (2 CLOROISOPROPIL) ETER
- [x] 117-81-7;BIS (ETILHELIX) FTALATO
- [x] 7440-42-8;BORO (TOTAL)
- [x] 1689-84-5;BROMOXIMIL
- [x] 7440-43-9;CADMIO (TOTAL)
- [x] 1563-66-2;CARBOFURANO
- [x] 21725-46-2;CIANAZINA
- [x] 7440-66-6;CINC (TOTAL)
- [x] 108-90-7;CLOROBENCENO
- [x] 2991-88-2;CLORPIRIFOS
- [x] 7440-50-8;COBRE (TOTAL)
- [x] 7440-47-3;CROMO (TOTAL)
- [x] 18540-29-9;CROMO (+6)
- [x] 333-41-5;DIAZINON
- [x] 106-93-4;DIBROMOETILENO
- [x] 1918-00-9;DICAMBA
- [x] 51338-27-3;DICLOFOP-METIL
- [x] 106-46-7;DICLOROBENCENO (1,4-)
- [x] 107-06-2;DICLOROETANO (1,2-)
- [x] 540-59-0;DICLOROETILENO (1,2-sis)
- [x] 156-60-5;DICLOROETILENO (1,2-trans)
- [x] 120-83-2;DICLOROFENOL (2,4-)
- [x] 563-54-2;DICLOROPROPILENO (1,2-)
- [x] 105-67-9;DIMETILFENOL (2,4-)
- [x] 121-14-2;DINITROTOLUENO (2,4-)
- [x] 330-54-1;DIURON
- [x] 100-42-5;ESTIRENO
- [x] 100-41-4;ETILBENCENO
- [x] 108-95-2;FENOL

- [x] 206-44-0;FLUORANTENO
- [x] 16984-48-8;FLUORURO (TOTAL)
- [x] 298-02-2;FORATO
- [x] 1071-83-6;GLIFOSATO
- [x] 1024-57-3;HEPTACLORO EPOXIDO
- [x] 118-74-1;HEXACLOROBENCENO
- [x] 7439-89-6;HIERRO (TOTAL)
- [x] 121-75-5;MALATION
- [x] 7439-96-5;MANGANESO (TOTAL)
- [x] 7439-97-6;MERCURIO (TOTAL)
- [x] 298-00-0;METIL PARATION
- [x] 51218-45-2;METOLACLOR
- [x] 21087-64-9;METRIBUZINA
- [ ] 7440-02-0;NIQUEL (TOTAL)
- [x] 1910-42-5;PARAQUAT
- [x] 1336-36-3;PCB (TOTAL)
- [ ] 12674-11-2;PCB - 1016 (AROCHLOR 1016)
- [ ] 11104-28-2;PCB - 1221 (AROCHLOR 1221)
- [ ] 11141-16-5;PCB - 1232 (AROCHLOR 1232)
- [x] 53469-21-9;PCB - 1242 (AROCHLOR 1242)
- [x] 12672-29-6;PCB - 1248 (AROCHLOR 1248)
- [ ] 11097-69-1;PCB - 1254 (AROCHLOR 1254)
- [x] 11096-82-5;PCB - 1260 (AROCHLOR 1260)
- [x] 608-93-5;PENTACLOROBENCENO
- [x] 7440-22-4;PLATA (TOTAL)
- [ ] 7439-92-1;PLOMO (TOTAL)
- [ ] 7782-49-2;SELENIO (TOTAL )
- [x] 122-34-9;SIMAZINE
- [ ] 7440-28-0;TALIO (TOTAL)
- [x] 3383-96-8;TEMEFOS
- [x] 13071-79-9;TERBUFOS
- [x] 127-18-4;TETRACLOROETILENO
- [x] 108-88-3;TOLUENO
- [ ] 8001-35-2;TOXAFENO
- [x] 2303-17-5;TRIALATO
- [x] 15950-66-0;TRICLOROFENOL (2,3,4-)
- [ ] 1330-20-7;XILENOS (TOTALES)0
- [x] 208-96-8;ACENAFTILENO
- [ ] 107-13-1;ACRILONITRILO
- [ ] 7440-36-0;ANTIMONIO (TOTAL)
- [x] 319-86-8;BHC-DELTA
- [x] 541-73-1;DICLOROBENCENO (1,3-)
- [x] 26638-19-7;DICLOROPROPANOS
- [ ] 26952-23-8;DICLOROPROPENOS
- [ ] 122-66-7;DIFENIL HIDRAZINA (1,2)
- [ ] 25321-14-6;DINITROTOLUENO
- [x] 959-98-8;ENDOSULFAN-ALFA
- [x] 33213-65-9;ENDOSULFAN-BETA
- [x] 608-73-1;HEXACLOROCICLOHEXANO (ISOMEROS)
- [x] 120-82-1;TRICLOROBENCENO (1,2,4-)
- [x] 25321-22-6;DICLOROBENCENO
- [x] 115-29-7;ENDOSULFAN
- [x] 7782-41-4;FLUOR
- [x] 7439-93-2;LITIO (TOTAL)
- [x] 205-99-2;BENZO(b)FLUORANTENO
- [x] 207-08-9;BENZO(K) FLUORANTANO
- [x] 7440-31-5;ESTAÑO
- [x] 193-39-5;INDENO(1,2,3-CD)PIRENO
- [x] 129-00-0;PIRENO
- [x] 108-05-4;ACETATO DE VINILO
- [x] 110-82-7;CICLOHEXANO
- [x] 7782-50-5;CLORO
- [x] 7647-01-0;CLORURO DE HIDROGENO
- [ ] 1319-77-3;CRESOLES
- [ ] 584-84-9;DI-ISOCIANATO DE TOLUENO
- [x] 7664-93-9;NIEBLA ACIDA (H2S04)
- [x] 7783-06-4;SULFURO DE HIDROGENO
- [ ] 740-47-3;CROMO

**Comment by luchomedrano** [comment]
Muestreo de compuestos y coinciden los datos nombres ID y textos.
